### ISSUE TITLE
No Such File or Directory

### ISSUE THREAD

**Issue by nahtnam** [ef4/ember-code-snippet#12]
Hey!

When my app auto-reloads, I get this error:
```
ENOENT: no such file or directory, stat '/home/nahtnam/Desktop/counter-strike/tmp/broccoli_merge_trees-input_base_path-P3j7pDdG.tmp/1/counter-strike/templates/components/code-snippet.hbs'
```

I have to manually go and restart `ctrl+c` + `ember server` to get it to work again.

Any fix?

Thanks.

**Comment by stefanpenner** [comment]
is there a full stacktrace?

**Comment by nahtnam** [comment]
Here is all the information I can find.

From the browser:
```
Error: ENOENT: no such file or directory, stat '/home/nahtnam/Desktop/counter-strike/tmp/broccoli_merge_trees-input_base_path-Rqon9ICX.tmp/1/counter-strike/templates/components/code-snippet.hbs'
    at Error (native)
    at Object.fs.statSync (fs.js:849:18)
    at checkIsDirectory (/home/nahtnam/Desktop/counter-strike/node_modules/ember-cli/node_modules/broccoli-merge-trees/index.js:149:17)
    at mergeRelativePath (/home/nahtnam/Desktop/counter-strike/node_modules/ember-cli/node_modules/broccoli-merge-trees/index.js:81:27)
    at mergeRelativePath (/home/nahtnam/Desktop/counter-strike/node_modules/ember-cli/node_modules/broccoli-merge-trees/index.js:128:15)
    at mergeRelativePath (/home/nahtnam/Desktop/counter-strike/node_modules/ember-cli/node_modules/broccoli-merge-trees/index.js:128:15)
    at mergeRelativePath (/home/nahtnam/Desktop/counter-strike/node_modules/ember-cli/node_modules/broccoli-merge-trees/index.js:128:15)
    at BroccoliMergeTrees.build (/home/nahtnam/Desktop/counter-strike/node_modules/ember-cli/node_modules/broccoli-merge-trees/index.js:26:3)
    at /home/nahtnam/Desktop/counter-strike/node_modules/ember-cli/node_modules/broccoli-merge-trees/node_modules/broccoli-plugin/read_compat.js:61:34
    at lib$rsvp$$internal$$tryCatch (/home/nahtnam/Desktop/counter-strike/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:493:16)
```

From console:
```
file changed controllers/settings.js
ENOENT: no such file or directory, stat '/home/nahtnam/Desktop/counter-strike/tmp/broccoli_merge_trees-input_base_path-Rqon9ICX.tmp/1/counter-strike/templates/components/code-snippet.hbs'
Error: ENOENT: no such file or directory, stat '/home/nahtnam/Desktop/counter-strike/tmp/broccoli_merge_trees-input_base_path-Rqon9ICX.tmp/1/counter-strike/templates/components/code-snippet.hbs'
    at Error (native)
    at Object.fs.statSync (fs.js:849:18)
    at checkIsDirectory (/home/nahtnam/Desktop/counter-strike/node_modules/ember-cli/node_modules/broccoli-merge-trees/index.js:149:17)
    at mergeRelativePath (/home/nahtnam/Desktop/counter-strike/node_modules/ember-cli/node_modules/broccoli-merge-trees/index.js:81:27)
    at mergeRelativePath (/home/nahtnam/Desktop/counter-strike/node_modules/ember-cli/node_modules/broccoli-merge-trees/index.js:128:15)
    at mergeRelativePath (/home/nahtnam/Desktop/counter-strike/node_modules/ember-cli/node_modules/broccoli-merge-trees/index.js:128:15)
    at mergeRelativePath (/home/nahtnam/Desktop/counter-strike/node_modules/ember-cli/node_modules/broccoli-merge-trees/index.js:128:15)
    at BroccoliMergeTrees.build (/home/nahtnam/Desktop/counter-strike/node_modules/ember-cli/node_modules/broccoli-merge-trees/index.js:26:3)
    at /home/nahtnam/Desktop/counter-strike/node_modules/ember-cli/node_modules/broccoli-merge-trees/node_modules/broccoli-plugin/read_compat.js:61:34
    at lib$rsvp$$internal$$tryCatch (/home/nahtnam/Desktop/counter-strike/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:493:16)
ENOENT: no such file or directory, stat '/home/nahtnam/Desktop/counter-strike/tmp/broccoli_merge_trees-input_base_path-Rqon9ICX.tmp/1/counter-strike/templates/components/code-snippet.hbs'
Error: ENOENT: no such file or directory, stat '/home/nahtnam/Desktop/counter-strike/tmp/broccoli_merge_trees-input_base_path-Rqon9ICX.tmp/1/counter-strike/templates/components/code-snippet.hbs'
    at Error (native)
    at Object.fs.statSync (fs.js:849:18)
    at checkIsDirectory (/home/nahtnam/Desktop/counter-strike/node_modules/ember-cli/node_modules/broccoli-merge-trees/index.js:149:17)
    at mergeRelativePath (/home/nahtnam/Desktop/counter-strike/node_modules/ember-cli/node_modules/broccoli-merge-trees/index.js:81:27)
    at mergeRelativePath (/home/nahtnam/Desktop/counter-strike/node_modules/ember-cli/node_modules/broccoli-merge-trees/index.js:128:15)
    at mergeRelativePath (/home/nahtnam/Desktop/counter-strike/node_modules/ember-cli/node_modules/broccoli-merge-trees/index.js:128:15)
    at mergeRelativePath (/home/nahtnam/Desktop/counter-strike/node_modules/ember-cli/node_modules/broccoli-merge-trees/index.js:128:15)
    at BroccoliMergeTrees.build (/home/nahtnam/Desktop/counter-strike/node_modules/ember-cli/node_modules/broccoli-merge-trees/index.js:26:3)
    at /home/nahtnam/Desktop/counter-strike/node_modules/ember-cli/node_modules/broccoli-merge-trees/node_modules/broccoli-plugin/read_compat.js:61:34
    at lib$rsvp$$internal$$tryCatch (/home/nahtnam/Desktop/counter-strike/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:493:16)
```

**Comment by ef4** [comment]
May be a dup of #10?

Does 1.1.1 (which uses a newer broccoli-merge-trees) still show the bug?

**Comment by stefanpenner** [comment]
Often explosions like this in merge trees can be the result of something upstream mutating inputPaths. Not always, but I've noticed it afew times recently. Leaking and polluting inputTrees may be worth investigating

**Comment by nahtnam** [comment]
Looks like upgrading to `1.1.1` from `1.1.0` fixed it!

Thanks.
