### ISSUE TITLE
adding ember-code-snippet as dependency throws error

### ISSUE THREAD

**Issue by mszoernyi** [ef4/ember-code-snippet#16]
Adding it as dependency (not devDependency) as suggested in https://github.com/ef4/ember-code-snippet/issues/4 throws the following error with `ember-cli 1.13.13`

```
version: 1.13.13
Cannot read property 'options' of undefined
TypeError: Cannot read property 'options' of undefined
    at Class.module.exports.snippetPaths (/home/mike/projects/remerge/ember-remerge/node_modules/ember-code-snippet/index.js:15:20)
    at Class.module.exports.treeForApp (/home/mike/projects/remerge/ember-remerge/node_modules/ember-code-snippet/index.js:24:35)
    at Class._treeFor (/home/mike/projects/remerge/ember-remerge/node_modules/ember-cli/lib/models/addon.js:319:31)
    at Class.treeFor (/home/mike/projects/remerge/ember-remerge/node_modules/ember-cli/lib/models/addon.js:289:19)
    at /home/mike/projects/remerge/ember-remerge/node_modules/ember-cli/lib/models/addon.js:242:32
    at Array.map (native)
    at Class.eachAddonInvoke (/home/mike/projects/remerge/ember-remerge/node_modules/ember-cli/lib/models/addon.js:240:22)
    at Class.treeFor (/home/mike/projects/remerge/ember-remerge/node_modules/ember-cli/lib/models/addon.js:287:20)
    at /home/mike/projects/remerge/ember-remerge/node_modules/ember-cli/lib/broccoli/ember-app.js:369:20
    at Array.map (native)
```

https://github.com/ef4/ember-code-snippet/blob/master/index.js#L15

**Comment by ef4** [comment]
Closing this because ember-cli now recommends using peerDependencies for recursive addon dependencies. 

https://github.com/ember-cli/ember-cli/issues/3718#issuecomment-166644137
