### ISSUE TITLE
Attempting to watch missing directory: tests/dummy/app

### ISSUE THREAD

**Issue by bryanhickerson** [ef4/ember-code-snippet#30]
After installing the addon with ember-cli 2.7.0 and I'm hitting this error when doing `ember serve`:

```
The Broccoli Plugin: [object Object] failed with:
Error: Attempting to watch missing directory: tests/dummy/app
    at EventEmitter.Watcher_addWatchDir [as addWatchDir] (/Users/bryan/src/betterup-app/frontend/node_modules/broccoli-sane-watcher/index.js:90:11)
    at /Users/bryan/src/betterup-app/frontend/node_modules/ember-cli-broccoli/lib/builder.js:95:35
    at lib$rsvp$$internal$$tryCatch (/Users/bryan/src/betterup-app/frontend/node_modules/rsvp/dist/rsvp.js:1036:16)
    at lib$rsvp$$internal$$invokeCallback (/Users/bryan/src/betterup-app/frontend/node_modules/rsvp/dist/rsvp.js:1048:17)
    at /Users/bryan/src/betterup-app/frontend/node_modules/rsvp/dist/rsvp.js:331:11
    at lib$rsvp$asap$$flush (/Users/bryan/src/betterup-app/frontend/node_modules/rsvp/dist/rsvp.js:1198:9)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)

The broccoli plugin was instantiated at:
undefined
```

Unclear on how to go about solving this. Is this because the addon is not a full fledged ember cli addon?

**Comment by bryanhickerson** [comment]
I was able to get around this by creating a `dummy/app` in the tests directory of my app.
