### ISSUE TITLE
Using in an addon fails

### ISSUE THREAD

**Issue by knownasilya** [ef4/ember-code-snippet#37]
I get the following:

```
 Cannot read property 'options' of undefined
TypeError: Cannot read property 'options' of undefined
    at Class.snippetPaths (/Users/iradchenko/sandbox/paper-origami/node_modules/ember-code-snippet/index.js:15:20)
    at Class.treeForApp (/Users/iradchenko/sandbox/paper-origami/node_modules/ember-code-snippet/index.js:30:36)
    at Class._treeFor (/Users/iradchenko/sandbox/paper-origami/node_modules/ember-cli/lib/models/addon.js:520:33)
    at Class.treeFor (/Users/iradchenko/sandbox/paper-origami/node_modules/ember-cli/lib/models/addon.js:480:21)
    at addons.map.addon (/Users/iradchenko/sandbox/paper-origami/node_modules/ember-cli/lib/models/addon.js:352:34)
    at Array.map (native)
    at Class.eachAddonInvoke (/Users/iradchenko/sandbox/paper-origami/node_modules/ember-cli/lib/models/addon.js:350:24)
    at Class.treeFor (/Users/iradchenko/sandbox/paper-origami/node_modules/ember-cli/lib/models/addon.js:479:22)
    at project.addons.map.addon (/Users/iradchenko/sandbox/paper-origami/node_modules/ember-cli/lib/broccoli/ember-app.js:547:22)
    at Array.map (native)
```

when using in an addon's `ember-cli-build.js`, like so:

```js
/* eslint-env node */
const EmberAddon = require('ember-cli/lib/broccoli/ember-addon');

module.exports = function(defaults) {
  var app = new EmberAddon(defaults, {
    snippetPaths: ['tests/dummy/snippets'],
    snippetSearchPaths: ['tests/dummy/app']
  });

  /*
    This build file specifies the options for the dummy test app of this
    addon, located in `/tests/dummy`
    This build file does *not* influence how the addon or the app using it
    behave. You most likely want to be modifying `./index.js` or app's build file
  */

  return app.toTree();
};
```

**Comment by mikemunsie** [comment]
I opened a PR for this: #38

**Comment by mikemunsie** [comment]
@knownasilya This issue has been resolved and is working in `v1.10.0` 👍

**Comment by knownasilya** [comment]
Woot!

**Comment by knownasilya** [comment]
Nice 👍
