### ISSUE TITLE
Using with an addon prevents `ember serve` from starting

### ISSUE THREAD

**Issue by taras** [ef4/ember-code-snippet#6]
I want to use this addon to document an addon and show code examples that I created in the addon's dummy app. After I install the addon in `dependencies`, I can't start the server because I get the following error:

```
ember serve
version: 0.2.3
Cannot read property 'options' of undefined
TypeError: Cannot read property 'options' of undefined
    at Class.module.exports.snippetPaths (/Users/tarasmankovski/Repositories/ember-cli-drg-ember-table/node_modules/ember-code-snippet/index.js:15:20)
    at Class.module.exports.treeForApp (/Users/tarasmankovski/Repositories/ember-cli-drg-ember-table/node_modules/ember-code-snippet/index.js:24:35)
    at Class._treeFor (/Users/tarasmankovski/Repositories/ember-cli-drg-ember-table/node_modules/ember-cli/lib/models/addon.js:315:31)
    at Class.treeFor (/Users/tarasmankovski/Repositories/ember-cli-drg-ember-table/node_modules/ember-cli/lib/models/addon.js:285:19)
    at /Users/tarasmankovski/Repositories/ember-cli-drg-ember-table/node_modules/ember-cli/lib/models/addon.js:238:32
    at Array.map (native)
    at Class.eachAddonInvoke (/Users/tarasmankovski/Repositories/ember-cli-drg-ember-table/node_modules/ember-cli/lib/models/addon.js:236:22)
    at Class.treeFor (/Users/tarasmankovski/Repositories/ember-cli-drg-ember-table/node_modules/ember-cli/lib/models/addon.js:283:20)
    at EmberAddon.<anonymous> (/Users/tarasmankovski/Repositories/ember-cli-drg-ember-table/node_modules/ember-cli/lib/broccoli/ember-app.js:342:20)
    at Array.map (native)
```

**Comment by taras** [comment]
nvm, I moved it to devDependencies and it works correctly.

**Comment by stefanpenner** [comment]
this exists, as to not leak these sorts of add-ons into the host app. If everyone addon's usage of ember-code-snippet leaked into the host app, many sad users would exist.
